# ===========================================
# MAPEAMENTOS DE COLEÇÕES MONGODB → MYSQL
# ===========================================

# Configuração para usuários
usuarios:
  mysql_table: "usuarios"
  create_table: true
  fields:
    _id: 
      mysql_field: "mongo_id"
      mysql_type: "VARCHAR(24)"
      transform: "str"
    nome:
      mysql_field: "nome"
      mysql_type: "VARCHAR(100)"
      required: true
      validate: "not_empty"
    email:
      mysql_field: "email"
      mysql_type: "VARCHAR(100)"
      required: true
      validate: "email"
      unique: true
    telefone:
      mysql_field: "telefone"
      mysql_type: "VARCHAR(20)"
      transform: "clean_phone"
    idade:
      mysql_field: "idade"
      mysql_type: "INT"
      validate: "positive_int"
    data_cadastro:
      mysql_field: "data_cadastro"
      mysql_type: "TIMESTAMP"
      default: "CURRENT_TIMESTAMP"
    ativo:
      mysql_field: "ativo"
      mysql_type: "BOOLEAN"
      default: true
  indexes:
    - fields: ["email"]
      unique: true
    - fields: ["mongo_id"]
      unique: true
  preserve_original: true

# Configuração para produtos
produtos:
  mysql_table: "produtos"
  create_table: true
  fields:
    _id:
      mysql_field: "mongo_id"
      mysql_type: "VARCHAR(24)"
      transform: "str"
    nome:
      mysql_field: "nome"
      mysql_type: "VARCHAR(200)"
      required: true
    descricao:
      mysql_field: "descricao"
      mysql_type: "TEXT"
    preco:
      mysql_field: "preco"
      mysql_type: "DECIMAL(10,2)"
      validate: "positive_decimal"
      transform: "to_decimal"
    categoria:
      mysql_field: "categoria"
      mysql_type: "VARCHAR(100)"
    tags:
      mysql_field: "tags"
      mysql_type: "JSON"
      transform: "array_to_json"
    ativo:
      mysql_field: "ativo"
      mysql_type: "BOOLEAN"
      default: true
    data_criacao:
      mysql_field: "data_criacao"
      mysql_type: "TIMESTAMP"
      default: "CURRENT_TIMESTAMP"
  indexes:
    - fields: ["categoria"]
    - fields: ["ativo"]
  preserve_original: true

# Configuração para pedidos
pedidos:
  mysql_table: "pedidos"
  create_table: true
  fields:
    _id:
      mysql_field: "mongo_id"
      mysql_type: "VARCHAR(24)"
    numero_pedido:
      mysql_field: "numero_pedido"
      mysql_type: "VARCHAR(50)"
      unique: true
    usuario_id:
      mysql_field: "usuario_id"
      mysql_type: "VARCHAR(24)"
      required: true
    produtos:
      mysql_field: "produtos"
      mysql_type: "JSON"
      transform: "array_to_json"
    total:
      mysql_field: "total"
      mysql_type: "DECIMAL(10,2)"
      validate: "positive_decimal"
    status:
      mysql_field: "status"
      mysql_type: "ENUM('pendente','processando','enviado','entregue','cancelado')"
      default: "pendente"
    data_pedido:
      mysql_field: "data_pedido"
      mysql_type: "TIMESTAMP"
      default: "CURRENT_TIMESTAMP"
  indexes:
    - fields: ["numero_pedido"]
      unique: true
    - fields: ["usuario_id"]
    - fields: ["status"]
  preserve_original: true

# Configuração para eventos/inscrições
inscricoes_eventos:
  mysql_table: "inscricoes_eventos"
  create_table: true
  fields:
    _id:
      mysql_field: "mongo_id"
      mysql_type: "VARCHAR(24)"
    nome:
      mysql_field: "nome"
      mysql_type: "VARCHAR(100)"
      required: true
    email:
      mysql_field: "email"
      mysql_type: "VARCHAR(100)"
      required: true
      validate: "email"
    telefone:
      mysql_field: "telefone"
      mysql_type: "VARCHAR(20)"
      transform: "clean_phone"
    evento:
      mysql_field: "evento"
      mysql_type: "VARCHAR(100)"
      default: "GeekFest 2025"
    tipo_ingresso:
      mysql_field: "tipo_ingresso"
      mysql_type: "ENUM('individual','vip','grupo')"
      default: "individual"
    data_inscricao:
      mysql_field: "data_inscricao"
      mysql_type: "TIMESTAMP"
      default: "CURRENT_TIMESTAMP"
    confirmado:
      mysql_field: "confirmado"
      mysql_type: "BOOLEAN"
      default: false
  indexes:
    - fields: ["email", "evento"]
      unique: true
    - fields: ["evento"]
  preserve_original: true

# ===========================================
# CONFIGURAÇÕES GLOBAIS
# ===========================================
global_settings:
  preserve_original_field: "dados_originais"
  preserve_original_type: "JSON"
  add_migration_timestamp: true
  migration_timestamp_field: "migrado_em"
  migration_timestamp_type: "TIMESTAMP"
  add_migration_id: true
  migration_id_field: "migracao_id"
  migration_id_type: "VARCHAR(36)"
